FactoryGirl.define do
  factory :location do
    name { Faker::Company.name.titleize }
    # address_1"
    # t.string   "address_2"
    # t.string   "city"
    # t.string   "state"
    # t.string   "zipcode"
    # t.string   "logo_url"
    # t.integer  "year_founded"
    # t.boolean  "provides_game_sound"
    # t.boolean  "provides_wifi"
    # t.boolean  "provides_power"
    # t.string   "tv_provider"
    # t.integer  "rating"
    # t.integer  "occupancy"
    # t.boolean  "smoking_allowed"
    # t.boolean  "staff_wear_colors"
    # t.integer  "tv_quantity"
    # t.integer  "high_definition"
    # t.integer  "sun_open_hour"
    # t.integer  "mon_open_hour"
    # t.integer  "tue_open_hour"
    # t.integer  "wed_open_hour"
    # t.integer  "thu_open_hour"
    # t.integer  "fri_open_hour"
    # t.integer  "sat_open_hour"
    # t.integer  "sun_close_hour"
    # t.integer  "mon_close_hour"
    # t.integer  "tue_close_hour"
    # t.integer  "wed_close_hour"
    # t.integer  "thu_close_hour"
    # t.integer  "fri_close_hour"
    # t.integer  "sat_close_hour"
    # t.string   "editor_note"
    # t.string   "website_url"
  end
end