defaults: &defaults
  app_name: "sports_bar"

test:
  <<: *defaults
  app_server: "Test"

development:
  <<: *defaults
  app_server: "Development"

staging:
  <<: *defaults
  app_server: "Staging"

production:
  <<: *defaults
  app_server: "Production"