development:
  adapter: postgresql
  host: localhost
  username: sports_bar
  database: sports_bar_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sports_bar_test
  username: sports_bar
